trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:

- job: build

  steps:
  
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'https://sonarcloud.io/project/configuration?id=MishaelHarrison_Co-Op-19-API'
      organization: 'mishaelharrison'
      scannerMode: 'MSBuild'
      projectKey: 'sonar.productkey'
    displayName: "compile cloud analisis"
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
    displayName: "dotnet build"

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
    displayName: "compile a publish"

  - task: SonarCloudAnalyze@1
    displayName: "publish cloud analisis"

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Pay-As-You-Go Dev/Test(3c1324b2-479b-4445-ba09-0814a6b4f9bd)'
      appType: 'webApp'
      WebAppName: 'DB-19'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    displayName: "publish app to azure webapps"

- job: test

  steps:
    
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'XUnit'
        testResultsFiles: '**/TEST-*.xml'